# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: echo "Test github action"
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed alexxsanya/udagram-api-feed:v1
    - run: docker tag udagram-api-user alexxsanya/udagram-api-user:v1
    - run: docker tag udagram-frontend:local alexxsanya/udagram-frontend:v1
    - run: docker tag reverseproxy alexxsanya/udagram-reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push alexxsanya/udagram-api-feed:v1
    - run: docker push alexxsanya/udagram-api-user:v1
    - run: docker push alexxsanya/udagram-frontend:v1
    - run: docker push alexxsanya/udagram-reverseproxy:v1